const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"班级管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBanji"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"备忘录类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBeiwanglu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"记事本类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJishiben"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"软件类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJisuanjizhuanyeruanjian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"课程类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKecheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"音乐类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYinyue"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"记事本管理",
                        "menuJump":"列表",
                        "tableName":"jishiben"
                    }
                ],
                "menu":"记事本管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"备忘录管理",
                        "menuJump":"列表",
                        "tableName":"beiwanglu"
                    }
                ],
                "menu":"备忘录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"计算机专业相关的软件管理",
                        "menuJump":"列表",
                        "tableName":"jisuanjizhuanyeruanjian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"计算机专业相关的软件留言管理",
                        "menuJump":"列表",
                        "tableName":"jisuanjizhuanyeruanjianLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"计算机专业相关的软件收藏管理",
                        "menuJump":"列表",
                        "tableName":"jisuanjizhuanyeruanjianCollection"
                    }
                ],
                "menu":"计算机专业相关的软件管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"课程管理",
                        "menuJump":"列表",
                        "tableName":"kecheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"课程留言管理",
                        "menuJump":"列表",
                        "tableName":"kechengLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"课程收藏管理",
                        "menuJump":"列表",
                        "tableName":"kechengCollection"
                    }
                ],
                "menu":"课程管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老师管理",
                        "menuJump":"列表",
                        "tableName":"laoshi"
                    }
                ],
                "menu":"老师管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿舍管理",
                        "menuJump":"列表",
                        "tableName":"sushe"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿舍人员管理",
                        "menuJump":"列表",
                        "tableName":"susheRenruan"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿舍归寝管理",
                        "menuJump":"列表",
                        "tableName":"susheGuiqin"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿舍报修管理",
                        "menuJump":"列表",
                        "tableName":"baoxiu"
                    }
                ],
                "menu":"宿舍管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"音乐管理",
                        "menuJump":"列表",
                        "tableName":"yinyue"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"音乐留言管理",
                        "menuJump":"列表",
                        "tableName":"yinyueLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"音乐收藏管理",
                        "menuJump":"列表",
                        "tableName":"yinyueCollection"
                    }
                ],
                "menu":"音乐管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"成绩管理",
                        "menuJump":"列表",
                        "tableName":"chengji"
                    }
                ],
                "menu":"成绩管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
,
{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"计算机专业相关的软件管理",
                        "menuJump":"列表",
                        "tableName":"jisuanjizhuanyeruanjian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"计算机专业相关的软件留言管理",
                        "menuJump":"列表",
                        "tableName":"jisuanjizhuanyeruanjianLiuyan"
                    }
                ],
                "menu":"计算机专业相关的软件管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"课程管理",
                        "menuJump":"列表",
                        "tableName":"kecheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"课程留言管理",
                        "menuJump":"列表",
                        "tableName":"kechengLiuyan"
                    }
                ],
                "menu":"课程管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿舍管理",
                        "menuJump":"列表",
                        "tableName":"sushe"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿舍人员管理",
                        "menuJump":"列表",
                        "tableName":"susheRenruan"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿舍归寝管理",
                        "menuJump":"列表",
                        "tableName":"susheGuiqin"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"宿舍报修管理",
                        "menuJump":"列表",
                        "tableName":"baoxiu"
                    }
                ],
                "menu":"宿舍管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"音乐管理",
                        "menuJump":"列表",
                        "tableName":"yinyue"
                    }
                ],
                "menu":"音乐管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"成绩管理",
                        "menuJump":"列表",
                        "tableName":"chengji"
                    }
                ],
                "menu":"成绩管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"老师",
        "tableName":"laoshi"
    }
,
{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"记事本管理",
                        "menuJump":"列表",
                        "tableName":"jishiben"
                    }
                ],
                "menu":"记事本管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"备忘录管理",
                        "menuJump":"列表",
                        "tableName":"beiwanglu"
                    }
                ],
                "menu":"备忘录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"计算机专业相关的软件管理",
                        "menuJump":"列表",
                        "tableName":"jisuanjizhuanyeruanjian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"计算机专业相关的软件留言管理",
                        "menuJump":"列表",
                        "tableName":"jisuanjizhuanyeruanjianLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"计算机专业相关的软件收藏管理",
                        "menuJump":"列表",
                        "tableName":"jisuanjizhuanyeruanjianCollection"
                    }
                ],
                "menu":"计算机专业相关的软件管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"课程管理",
                        "menuJump":"列表",
                        "tableName":"kecheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"课程留言管理",
                        "menuJump":"列表",
                        "tableName":"kechengLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"课程收藏管理",
                        "menuJump":"列表",
                        "tableName":"kechengCollection"
                    }
                ],
                "menu":"课程管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"宿舍人员管理",
                        "menuJump":"列表",
                        "tableName":"susheRenruan"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"宿舍归寝管理",
                        "menuJump":"列表",
                        "tableName":"susheGuiqin"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"宿舍报修管理",
                        "menuJump":"列表",
                        "tableName":"baoxiu"
                    }
                ],
                "menu":"宿舍管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"音乐管理",
                        "menuJump":"列表",
                        "tableName":"yinyue"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"音乐留言管理",
                        "menuJump":"列表",
                        "tableName":"yinyueLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"音乐收藏管理",
                        "menuJump":"列表",
                        "tableName":"yinyueCollection"
                    }
                ],
                "menu":"音乐管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"成绩管理",
                        "menuJump":"列表",
                        "tableName":"chengji"
                    }
                ],
                "menu":"成绩管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
